name: “And Another Thing…”
description: "A blog about automation and Chef and technology culture."
url: http://andanotherthing.github.io
markdown: redcarpet
highlighter: pygments
paginate: 5
permalink: /:title
disqus-id: andanotherthingblog
twitter: kevindickerson
github: kevindickerson
rss-feed-limit: 20
rss-show-full: "yes"
