# Site settings
title: “And Another Thing…”
email: kevin.dickerson@protonmail.ch
description: >
  A blog about automation and Chef and technology culture.
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://andanotherthing.github.io
twitter_username: kevindickerson
github_username: kevindickerson
disqus_shortname: andanotherthingblog
# Build settings
markdown: kramdown
permalink: :title